### ISSUE TITLE
Unsupported operation: Infinity or NaN toInt

### ISSUE THREAD

**Issue by VadymPinchuk** [Milad-Akarie/smooth_page_indicator#84]
```
The following UnsupportedError was thrown during paint():
Unsupported operation: Infinity or NaN toInt

When the exception was thrown, this was the stack: 
#0      double.floor (dart:core-patch/double.dart)
#1      ScrollingDotsPainter.paint (package:smooth_page_indicator/src/painters/scrolling_dots_painter.dart:31:34)
#2      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:588:13)
#3      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:630:7)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3239:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#6      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:130:13)
#7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3239:7)
```

**Comment by jay-mahakalagro** [comment]
Facing Same Issue . Please help to resolve it

**Comment by Milad-Akarie** [comment]
@VadymPinchuk @jay-mahakalagro are you using `AnimatedSmoothIndicator` or `SmoothPageIndicator`?

**Comment by mrjanees** [comment]
Facing the Same Issue. I am using AnimatedSmoothIndicator. My Flutter version is 3.22.3 . Dart 3.4.4 and smooth_page_indicator: ^1.2.0. How to solve this issue?

**Comment by mrjanees** [comment]
Any solution?

**Comment by VadymPinchuk** [comment]
```
SmoothPageIndicator(
          controller: pageController,
          count: pageCount,
          effect: ScrollingDotsEffect(
            maxVisibleDots: 7,
            activeDotScale: 1.0,
            dotHeight: dimens.indicatorDotSize,
            dotWidth: dimens.indicatorDotSize,
            spacing: dimens.indicatorDotSize * 2,
            dotColor: theme.colors.baseLight30,
            activeDotColor: theme.colors.baseLightPrimary,
          ),
        )
```
        
        
this is my code. 
In regards of Flutter - I am on the main branch :) need it for work. But on 3.24 it was the same
@Milad-Akarie  can you check it out? 
Thanks

**Comment by ProjectHousePC** [comment]
Firebase crashlytics keep spamming this error yet....

**Comment by passos** [comment]
send a fix in pull request #87

**Comment by VadymPinchuk** [comment]
@Milad-Akarie  could you check this PR.
